# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/LogEntry/'
            - '../src/Domain/LogSinker/LogEntry.php'
            - '../src/Shared/'
            - '../src/Kernel.php'

    App\Infrastructure\ExceptionHandler\:
        resource: '../src/Infrastructure/ExceptionHandler/'
        tags: [ 'app.exception_handler' ]

    App\Infrastructure\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Infrastructure\ExceptionHandler\ExceptionHandlerResolver:
        arguments:
            $handlers: !tagged_iterator app.exception_handler

    App\Infrastructure\Serializer\CarbonDateTimeDenormalizer:
        tags: [ serializer.normalizer ]

    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: [ 'doctrine.fixture.orm' ]

    _instanceof:
        App\Application\Command\Handler\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Application\Query\Handler\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
