framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - 'doctrine_transaction'
            query.bus:

        transports:
            async_command:
                dsn: 'doctrine://default'
                options:
                    table_name: messenger_messages
                    queue_name: commands
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

        routing:
            'App\Application\Command\*': async_command
